[features]
seeds = false
[programs.localnet]
solana_twitter = "FT1tUCwE18boUgi8pdbriSsnTUXEjLJcpbsEhUn575cQ"
[programs.devnet]
solana_twitter = "FT1tUCwE18boUgi8pdbriSsnTUXEjLJcpbsEhUn575cQ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/jaylee/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"